// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextScanner.FileAnalysisService.Data;

#nullable disable

namespace TextScanner.FileAnalysisService.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20250525153824_UpdateAnalysisResult")]
    partial class UpdateAnalysisResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TextScanner.FileAnalysisService.Models.AnalysisResult", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParagraphCount")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("FileId");

                    b.ToTable("AnalysisResults", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
